version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: tablemate-postgres
    restart: always

    environment:
      POSTGRES_USER: tablemate
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tablemate

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: