spring:
  application:
    name: TableMate

  datasource:
    url: jdbc:postgresql://localhost:55432/tablemate
    username: tablemate
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: tablemate-jwt-secret-key-very-long-at-least-256-bits-required-for-hs256-algorithm
  expiration: 86400000

server:
  port: 8080
